use crate::question::Question;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Difficulty {
    Easy,
    #[default]
    Normal,
    Hard,
}

impl Difficulty {
    pub fn label(&self) -> &'static str {
        match self {
            Difficulty::Easy => "イージー (3-6文字)",
            Difficulty::Normal => "ノーマル (7-11文字)",
            Difficulty::Hard => "ハード (12文字以上)",
        }
    }

    pub fn pool(&self) -> Vec<Question> {
        match self {
            Difficulty::Easy => easy_pool(),
            Difficulty::Normal => normal_pool(),
            Difficulty::Hard => hard_pool(),
        }
    }
}

// ========================================================
// Easy（初級：3〜6文字）
// ========================================================
pub fn easy_pool() -> Vec<Question> {
    vec![
        Question::from_ruby("[青|あお][空|ぞら]"),
        Question::from_ruby("[朝|あさ][顔|がお]"),
        Question::from_ruby("[足|あし]が[出|で]る"),
        Question::from_ruby("[紫陽花|あじさい]"),
        Question::from_ruby("[油|あぶら]を[売|う]る"),
        Question::from_ruby("[飴|あめ]と[鞭|むち]"),
        Question::from_ruby("[息|いき]を[呑|の]む"),
        Question::from_ruby("[一|いち]か[八|ばち]か"),
        Question::from_ruby("イチゴ"),
        Question::from_ruby("[一|いち][期|ご][一|いち][会|え]"),
        Question::from_ruby("[犬|いぬ][死|じ]に"),
        Question::from_ruby("[馬|うま]が[合|あ]う"),
        Question::from_ruby("[海|うみ]ほたる"),
        Question::from_ruby("[枝|えだ][豆|まめ]"),
        Question::from_ruby("お[好|この]み[焼|や]き"),
        Question::from_ruby("お[寿|す][司|し]"),
        Question::from_ruby("おにぎり"),
        Question::from_ruby("お[弁|べん][当|とう]"),
        Question::from_ruby("[温|おん][故|こ][知|ち][新|しん]"),
        Question::from_ruby("[顔|かお]が[広|ひろ]い"),
        Question::from_ruby("[風邪|かぜ][薬|ぐすり]"),
        Question::from_ruby("カステラ"),
        Question::from_ruby("カボチャ"),
        Question::from_ruby("カレーライス"),
        Question::from_ruby("[気|き]がおけない"),
        Question::from_ruby("[気|き]が[長|なが]い"),
        Question::from_ruby("[気|き]が[短|みじか]い"),
        Question::from_ruby("キャベツ"),
        Question::from_ruby("キュウリ"),
        Question::from_ruby("[金|きん][魚|ぎょ]"),
        Question::from_ruby("[疑|ぎ][心|しん][暗|あん][鬼|き]"),
        Question::from_ruby("[釘|くぎ]を[刺|さ]す"),
        Question::from_ruby("クッキー"),
        Question::from_ruby("[口|くち]が[滑|すべ]る"),
        Question::from_ruby("[首|くび]をひねる"),
        Question::from_ruby("[車|くるま]"),
        Question::from_ruby("ケーキ"),
        Question::from_ruby("[孤|こ][立|りつ][無|む][援|えん]"),
        Question::from_ruby("ごますり"),
        Question::from_ruby("[五|ご][里|り][霧|む][中|ちゅう]"),
        Question::from_ruby("[桜|さくら]"),
        Question::from_ruby("[猿|さる]まね"),
        Question::from_ruby("サンドイッチ"),
        Question::from_ruby("[塩|しお]を[送|おく]る"),
        Question::from_ruby("[舌|した]を[巻|ま]く"),
        Question::from_ruby("[四|し][面|めん][楚|そ][歌|か]"),
        Question::from_ruby("シャボン[玉|だま]"),
        Question::from_ruby("[新|しん][幹|かん][線|せん]"),
        Question::from_ruby("[自|じ][業|ごう][自|じ][得|とく]"),
        Question::from_ruby("[自|じ][転|てん][車|しゃ]"),
        Question::from_ruby("ジャガイモ"),
        Question::from_ruby("スイカ"),
        Question::from_ruby("すき[焼|や]き"),
        Question::from_ruby("[切|せっ][磋|さ][琢|たく][磨|ま]"),
        Question::from_ruby("そうめん"),
        Question::from_ruby("たい[焼|や]き"),
        Question::from_ruby("[太|たい][陽|よう]"),
        Question::from_ruby("たこ[焼|や]き"),
        Question::from_ruby("タマネギ"),
        Question::from_ruby("[狸|たぬき][寝|ね][入|い]り"),
        Question::from_ruby("タンポポ"),
        Question::from_ruby("[大|だい][根|こん]"),
        Question::from_ruby("チョコレート"),
        Question::from_ruby("[月|つき][見|み]うどん"),
        Question::from_ruby("[手|て][前|まえ][味|み][噌|そ]"),
        Question::from_ruby("[手|て]を[抜|ぬ]く"),
        Question::from_ruby("[電|でん][車|しゃ]"),
        Question::from_ruby("トマト"),
        Question::from_ruby("[鶏|とり][肉|にく]"),
        Question::from_ruby("ドーナツ"),
        Question::from_ruby("どら[焼|や]き"),
        Question::from_ruby("どんぐり"),
        Question::from_ruby("ナス"),
        Question::from_ruby("ニンジン"),
        Question::from_ruby("[糠|ぬか]に[釘|くぎ]"),
        Question::from_ruby("[猫|ねこ][背|ぜ]"),
        Question::from_ruby("[猫|ねこ]の[額|ひたい]"),
        Question::from_ruby("[猫|ねこ]に[小|こ][判|ばん]"),
        Question::from_ruby("[猫|ねこ]をかぶる"),
        Question::from_ruby("[音|ね]を[上|あ]げる"),
        Question::from_ruby("[歯|は]が[立|た]たない"),
        Question::from_ruby("[鼻|はな]で[笑|わら]う"),
        Question::from_ruby("[花|はな][火|び]"),
        Question::from_ruby("[花|はな]びら"),
        Question::from_ruby("ハンバーガー"),
        Question::from_ruby("[腹|はら]を[割|わ]る"),
        Question::from_ruby("バナナ"),
        Question::from_ruby("[飛|ひ][行|こう][機|き]"),
        Question::from_ruby("ヒマワリ"),
        Question::from_ruby("ブドウ"),
        Question::from_ruby("プリン"),
        Question::from_ruby("ホウレンソウ"),
        Question::from_ruby("[星|ほし][空|ぞら]"),
        Question::from_ruby("ホタル"),
        Question::from_ruby("[祭|まつ]り"),
        Question::from_ruby("ミカン"),
        Question::from_ruby("[水|みず]に[流|なが]す"),
        Question::from_ruby("[耳|みみ]を[貸|か]す"),
        Question::from_ruby("[無|む][我|が][夢|む][中|ちゅう]"),
        Question::from_ruby("[目|め]をつぶる"),
        Question::from_ruby("[目|め]を[疑|うたが]う"),
        Question::from_ruby("メロン"),
        Question::from_ruby("[焼|や]きそば"),
        Question::from_ruby("[焼|や]き[肉|にく]"),
        Question::from_ruby("リンゴ"),
        Question::from_ruby("わらび[餅|もち]"),
    ]
}

// ========================================================
// Normal（中級：7〜11文字）
// ========================================================
pub fn normal_pool() -> Vec<Question> {
    vec![
        Question::from_ruby("アイスクリーム"),
        Question::from_ruby("[秋|あき]の[夕|ゆう][暮|ぐ]れ"),
        Question::from_ruby("[朝|あさ]ごはんを[食|た]べる"),
        Question::from_ruby("[足|あし]を[引|ひ]っ[張|ぱ]る"),
        Question::from_ruby("[頭|あたま]を[抱|かか]える"),
        Question::from_ruby("[雨|あめ][上|あ]がりの[虹|にじ]"),
        Question::from_ruby("[雨|あめ][降|ふ]って[地|じ][固|かた]まる"),
        Question::from_ruby("[暗|あん][中|ちゅう][模|も][索|さく]"),
        Question::from_ruby("[石|いし]の[上|うえ]にも[三|さん][年|ねん]"),
        Question::from_ruby("[以|い][心|しん][伝|でん][心|しん]"),
        Question::from_ruby("[急|いそ]がば[回|まわ]れ"),
        Question::from_ruby("[一|いっ][寸|すん][先|さき]は[闇|やみ]"),
        Question::from_ruby("[一|いっ][石|せき][二|に][鳥|ちょう]"),
        Question::from_ruby("[一|いっ][生|しょう][懸|けん][命|めい]"),
        Question::from_ruby("[犬|いぬ]の[遠|とお][吠|ぼ]え"),
        Question::from_ruby("[犬|いぬ]も[食|く]わない"),
        Question::from_ruby("[因|いん][果|が][応|おう][報|ほう]"),
        Question::from_ruby("[腕|うで]の[見|み]せ[所|どころ]"),
        Question::from_ruby("ウナギの[寝|ね][床|どこ]"),
        Question::from_ruby("[馬|うま]の[耳|みみ]に[念|ねん][仏|ぶつ]"),
        Question::from_ruby("[海|うみ]を[眺|なが]める"),
        Question::from_ruby("[映|えい][画|が]を[見|み]に[行|い]く"),
        Question::from_ruby("[絵|え]に[描|か]いた[餅|もち]"),
        Question::from_ruby("[大|おお][当|あ]たりを[引|ひ]く"),
        Question::from_ruby("お[茶|ちゃ]を[飲|の]んで[一|ひと][休|やす]み"),
        Question::from_ruby("お[疲|つか]れさまでした"),
        Question::from_ruby("[鬼|おに]に[金|かな][棒|ぼう]"),
        Question::from_ruby("お[弁|べん][当|とう]を[作|つく]る"),
        Question::from_ruby("[音|おん][楽|がく]を[聴|き]く"),
        Question::from_ruby("[温|おん][泉|せん][旅|りょ][行|こう]"),
        Question::from_ruby("[恩|おん]を[仇|あだ]で[返|かえ]す"),
        Question::from_ruby("[海|かい][外|がい][旅|りょ][行|こう]"),
        Question::from_ruby("[蛙|かえる]の[子|こ]は[蛙|かえる]"),
        Question::from_ruby("[火|か][事|じ][場|ば]の[馬|ば][鹿|か][力|じから]"),
        Question::from_ruby("[肩|かた]の[荷|に]を[下|お]ろす"),
        Question::from_ruby("[果|か][報|ほう]は[寝|ね]て[待|ま]て"),
        Question::from_ruby("[川|かわ]のせせらぎ"),
        Question::from_ruby("ギターを[鳴|な]らす"),
        Question::from_ruby("[逆|ぎゃく][転|てん]ホームラン"),
        Question::from_ruby("[腐|くさ]っても[鯛|たい]"),
        Question::from_ruby("[口|くち]は[災|わざわ]いのもと"),
        Question::from_ruby("[犬|けん][猿|えん]の[仲|なか]"),
        Question::from_ruby("コーヒーを[飲|の]む"),
        Question::from_ruby("[心|こころ]を[一|ひと]つにする"),
        Question::from_ruby("[桜|さくら]の[咲|さ]く[季|き][節|せつ]"),
        Question::from_ruby("[猿|さる]も[木|き]から[落|お]ちる"),
        Question::from_ruby("しっぽを[掴|つか]む"),
        Question::from_ruby("[写|しゃ][真|しん]を[撮|と]る"),
        Question::from_ruby("[弱|じゃく][肉|にく][強|きょう][食|しょく]"),
        Question::from_ruby("[十|じゅう][人|にん][十|と][色|いろ]"),
        Question::from_ruby("[順|じゅん][風|ぷう][満|まん][帆|ぱん]"),
        Question::from_ruby("シュークリーム"),
        Question::from_ruby("[食|しょく][欲|よく]の[秋|あき]"),
        Question::from_ruby("[雀|すずめ]の[涙|なみだ]"),
        Question::from_ruby("スポーツの[秋|あき]"),
        Question::from_ruby("[千|せん][載|ざい][一|いち][遇|ぐう]"),
        Question::from_ruby("[前|ぜん][代|だい][未|み][聞|もん]"),
        Question::from_ruby("[全|ぜん][身|しん][全|ぜん][霊|れい]"),
        Question::from_ruby("[大|たい][器|き][晩|ばん][成|せい]"),
        Question::from_ruby("[棚|たな]からぼたもち"),
        Question::from_ruby("[猪|ちょ][突|とつ][猛|もう][進|しん]"),
        Question::from_ruby("[月|つき]とスッポン"),
        Question::from_ruby("[手|て][紙|がみ]を[書|か]き[送|おく]る"),
        Question::from_ruby("[手|て]のひらを[返|かえ]す"),
        Question::from_ruby("[電|でん][話|わ]をかける"),
        Question::from_ruby("[東|とう][京|きょう]タワー"),
        Question::from_ruby("[虎|とら]の[威|い]を[借|か]る[狐|きつね]"),
        Question::from_ruby("ドングリの[背|せい][比|くら]べ"),
        Question::from_ruby("[七|なな][転|ころ]び[八|や][起|お]き"),
        Question::from_ruby("[二|に][人|にん][三|さん][脚|きゃく]"),
        Question::from_ruby("[糠|ぬか]に[釘|くぎ]を[打|う]つ"),
        Question::from_ruby("[猫|ねこ]の[手|て]も[借|か]りたい"),
        Question::from_ruby("のれんに[腕|うで][押|お]し"),
        Question::from_ruby("ハチミツレモン"),
        Question::from_ruby("[花|はな][火|び][大|たい][会|かい]"),
        Question::from_ruby("[花|はな]を[持|も]たせる"),
        Question::from_ruby("[花|はな]より[団|だん][子|ご]"),
        Question::from_ruby("[八|はっ][方|ぽう][美|び][人|じん]"),
        Question::from_ruby("[早|はや][起|お]きは[三|さん][文|もん]の[得|とく]"),
        Question::from_ruby("[春|はる]の[足|あし][音|おと]"),
        Question::from_ruby("[晩|ばん]ごはんの[支|し][度|たく]"),
        Question::from_ruby("[火|ひ]に[油|あぶら]を[注|そそ]ぐ"),
        Question::from_ruby("ピアノの[演|えん][奏|そう]"),
        Question::from_ruby("[富|ふ][士|じ][山|さん]を[登|のぼ]る"),
        Question::from_ruby("[冬|ふゆ]の[朝|あさ][焼|や]け"),
        Question::from_ruby("[豚|ぶた]に[真|しん][珠|じゅ]"),
        Question::from_ruby("[星|ほし][空|ぞら]を[見|み][上|あ]げる"),
        Question::from_ruby("[本|ほん]を[読|よ]み[進|すす]める"),
        Question::from_ruby("[真|ま][夏|なつ]の[日|ひ][差|ざ]し"),
        Question::from_ruby("[身|み]から[出|で]た[錆|さび]"),
        Question::from_ruby("みたらし[団|だん][子|ご]"),
        Question::from_ruby("[耳|みみ]にタコができる"),
        Question::from_ruby("メールを[送|おく]る"),
        Question::from_ruby("[目|め]を[閉|と]じて[考|かんが]える"),
        Question::from_ruby("[目|め]を[丸|まる]くする"),
        Question::from_ruby("[紅葉|もみじ][狩|が]りへ[行|い]く"),
        Question::from_ruby("[森|もり]の[中|なか]を[歩|ある]く"),
        Question::from_ruby("[優|ゆう][柔|じゅう][不|ふ][断|だん]"),
        Question::from_ruby("[夕|ゆう][焼|や]け[小|こ][焼|や]け"),
        Question::from_ruby("[雪|ゆき]だるまを[作|つく]る"),
        Question::from_ruby("[夢|ゆめ]を[追|お]いかける"),
        Question::from_ruby("[両|りょう][手|て]に[花|はな]"),
        Question::from_ruby("[臨|りん][機|き][応|おう][変|へん]"),
    ]
}

// ========================================================
// Hard（上級：12文字以上）
// ========================================================
pub fn hard_pool() -> Vec<Question> {
    vec![
        Question::from_ruby("[開|あ]いた[口|くち]がふさがらない"),
        Question::from_ruby("[青|あお][空|ぞら]の[下|もと]でおもいきり[体|からだ]を[動|うご]かす"),
        Question::from_ruby(
            "[赤|あか][巻|まき][紙|がみ][青|あお][巻|まき][紙|がみ][黄|き][巻|まき][紙|がみ]",
        ),
        Question::from_ruby("[秋|あき]の[夜|よ][長|なが]に[好|す]きな[本|ほん]をじっくり[読|よ]む"),
        Question::from_ruby("[朝|あさ]の[光|ひかり]を[浴|あ]びてすっきり[目|め][覚|ざ]める"),
        Question::from_ruby("[明日|あした]の[自|じ][分|ぶん]をもっと[好|す]きになるために"),
        Question::from_ruby("[明日|あした]の[天|てん][気|き]はどうでしょうか"),
        Question::from_ruby("[明日|あした]は[明日|あした]の[風|かぜ]が[吹|ふ]く"),
        Question::from_ruby("[明日|あす]への[希|き][望|ぼう]を[胸|むね]に[生|い]きていく"),
        Question::from_ruby("[焦|あせ]らず[自|じ][分|ぶん]のペースで[進|すす]めましょう"),
        Question::from_ruby(
            "[新|あたら]しい[出|で][会|あ]いが[人|じん][生|せい]を[豊|ゆた]かにする",
        ),
        Question::from_ruby("[新|あたら]しい[挑|ちょう][戦|せん]に[向|む]けてがんばります"),
        Question::from_ruby(
            "[新|あたら]しい[本|ほん]を[買|か]って[帰|かえ]り[道|みち]を[急|いそ]ぐ",
        ),
        Question::from_ruby("[温|あたた]かいお[茶|ちゃ]を[飲|の]んでほっと[一|ひと][息|いき]"),
        Question::from_ruby("[頭|あたま][隠|かく]して[尻|しり][隠|かく]さず"),
        Question::from_ruby(
            "[雨|あめ]の[日|ひ]も[風|かぜ]の[日|ひ]も[毎|まい][日|にち][走|はし]る",
        ),
        Question::from_ruby("[案|あん]ずるより[産|う]むが[易|やす]し"),
        Question::from_ruby("[一|いち][日|にち]の[計|けい]は[朝|あさ]にあり"),
        Question::from_ruby("[一|いち][富|ふ][士|じ][二|に][鷹|たか][三|さん][茄|な][子|すび]"),
        Question::from_ruby("[一|いっ][寸|すん]の[虫|むし]にも[五|ご][分|ぶ]の[魂|たましい]"),
        Question::from_ruby("いつも[温|あたた]かいご[支|し][援|えん]をありがとうございます"),
        Question::from_ruby("いつもお[仕|し][事|ごと]ご[苦|く][労|ろう][様|さま]です"),
        Question::from_ruby("いつも[大|たい][変|へん]お[世|せ][話|わ]になっております"),
        Question::from_ruby("[犬|いぬ]もあるけば[棒|ぼう]に[当|あ]たる"),
        Question::from_ruby("イワシの[頭|あたま]も[信|しん][心|じん]から"),
        Question::from_ruby("うそつきは[泥|どろ][棒|ぼう]の[始|はじ]まり"),
        Question::from_ruby("[笑|え][顔|がお]を[忘|わす]れずに[毎|まい][日|にち]を[過|すご]す"),
        Question::from_ruby("おいしいごはんを[食|た]べて[元|げん][気|き]を[出|だ]そう"),
        Question::from_ruby("お[気|き]に[入|い]りの[音|おん][楽|がく]を[聴|き]きながら[歩|ある]く"),
        Question::from_ruby("[溺|おぼ]れる[者|もの]はわらをも[掴|つか]む"),
        Question::from_ruby("[思|おも]い[出|で]はいつまでも[胸|むね]の[中|なか]に[残|のこ]る"),
        Question::from_ruby("お[返|へん][事|じ]をお[待|ま]ちしております"),
        Question::from_ruby("[輝|かがや]く[星|ほし]を[見|み][上|あ]げて[願|ねが]い[事|ごと]をする"),
        Question::from_ruby(
            "[蛙|かえる]ぴょこぴょこ[三|み]ぴょこぴょこ[合|あ]わせてぴょこぴょこ[六|む]ぴょこぴょこ",
        ),
        Question::from_ruby("[家|か][族|ぞく]みんなで[楽|たの]しく[食|しょく][事|じ]をする"),
        Question::from_ruby("[金|かね]の[切|き]れ[目|め]が[縁|えん]の[切|き]れ[目|め]"),
        Question::from_ruby("[鴨|かも]がネギを[背負|しょ]ってくる"),
        Question::from_ruby("[亀|かめ]の[甲|こう]より[年|とし]の[功|こう]"),
        Question::from_ruby("[変|か]わらぬ[愛|あい]を[送|おく]ります"),
        Question::from_ruby(
            "[聞|き]くは[一|いっ][時|とき]の[恥|はじ][聞|き]かぬは[一|いっ][生|しょう]の[恥|はじ]",
        ),
        Question::from_ruby(
            "[季|き][節|せつ]の[変|か]わり[目|め]ですのでご[自|じ][愛|あい]ください",
        ),
        Question::from_ruby("[季|き][節|せつ]の[風|かぜ]を[感|かん]じながら[散|さん][歩|ぽ]する"),
        Question::from_ruby("[今日|きょう]は[一|いち][日|にち]お[疲|つか]れさまでした"),
        Question::from_ruby("[今日|きょう]はとてもいい[天|てん][気|き]ですね"),
        Question::from_ruby("[口|くち][八|はっ][丁|ちょう][手|て][八|はっ][丁|ちょう]"),
        Question::from_ruby("[心|こころ]を[落|お]ち[着|つ]かせて[深|しん][呼|こ][吸|きゅう]をする"),
        Question::from_ruby("[心|こころ]の[赴|おもむ]くままに[旅|たび]をする"),
        Question::from_ruby("[子|こ][供|ども]のころの[夢|ゆめ]を[今|いま]でも[覚|おぼ]えている"),
        Question::from_ruby("[困|こま]ったときはお[互|たが]い[様|さま]です"),
        Question::from_ruby("これからもよろしくお[願|ねが]いいたします"),
        Question::from_ruby("[郷|ごう]に[入|い]っては[郷|ごう]に[従|したが]え"),
        Question::from_ruby("ご[確|かく][認|にん]のほどよろしくお[願|ねが]いします"),
        Question::from_ruby("ご[検|けん][討|とう]のほどよろしくお[願|ねが]いいたします"),
        Question::from_ruby("[今|こん][後|ご]ともよろしくお[願|ねが]い[申|もう]し[上|あ]げます"),
        Question::from_ruby("[時|じ][間|かん]とお[金|かね]のむだづかい"),
        Question::from_ruby("[自|じ][分|ぶん]の[力|ちから]を[信|しん]じて[前|まえ]に[進|すす]む"),
        Question::from_ruby(
            "[自|じ][分|ぶん]らしく[生|い]きることが[一|いち][番|ばん][大|たい][切|せつ]",
        ),
        Question::from_ruby("[静|しず]かな[夜|よる]に[星|ほし][空|ぞら]を[眺|なが]める"),
        Question::from_ruby(
            "[静|しず]かな[図|と][書|しょ][館|かん]で[時|じ][間|かん]を[忘|わす]れて[過|すご]す",
        ),
        Question::from_ruby(
            "[失|しっ][敗|ぱい]を[恐|おそ]れずに[一|いっ][歩|ぽ]を[踏|ふ]み[出|だ]す",
        ),
        Question::from_ruby(
            "[新|しん][人|じん][歌|か][手|しゅ][新|しん][春|しゅん]シャンソンショー",
        ),
        Question::from_ruby("[心|しん][配|ぱい][事|ごと]がなくなって[安|あん][心|しん]した"),
        Question::from_ruby("[好|す]きなことに[夢|む][中|ちゅう]になる[時|じ][間|かん]"),
        Question::from_ruby("[少|すこ]し[休|やす]んでお[茶|ちゃ]にしましょう"),
        Question::from_ruby(
            "[素|す][直|なお]な[気|き][持|も]ちを[伝|つた]えることが[大|たい][切|せつ]",
        ),
        Question::from_ruby("すもももももも[桃|もも]のうち"),
        Question::from_ruby("[暑|しょ][中|ちゅう]お[見|み][舞|ま]い[申|もう]し[上|あ]げます"),
        Question::from_ruby("[千|せん][里|り]の[道|みち]も[一|いっ][歩|ぽ]から"),
        Question::from_ruby("[大|たい][切|せつ]な[人|ひと]の[幸|しあわ]せを[願|ねが]う"),
        Question::from_ruby("[楽|たの]しい[思|おも]い[出|で]をたくさん[作|つく]りましょう"),
        Question::from_ruby("[助|たす]け[合|あ]いの[心|こころ]を[大|たい][切|せつ]にしましょう"),
        Question::from_ruby("[塵|ちり]も[積|つ]もれば[山|やま]となる"),
        Question::from_ruby("[東|とう][京|きょう][特|とっ][許|きょ][許|きょ][可|か][局|きょく]"),
        Question::from_ruby("[動|どう][物|ぶつ]たちとふれあって[心|こころ]を[癒|いや]す"),
        Question::from_ruby("どうぞよい[週|しゅう][末|まつ]をお[過|すご]しください"),
        Question::from_ruby("[通|とお]り[雨|あめ]が[過|す]ぎて[青|あお][空|ぞら]が[広|ひろ]がる"),
        Question::from_ruby("どこまでも[続|つづ]く[青|あお]い[空|そら]を[見|み][上|あ]げる"),
        Question::from_ruby("[努|ど][力|りょく]はきっといつか[報|むく]われる"),
        Question::from_ruby("どんな[困|こん][難|なん]にも[負|ま]けずに[立|た]ち[向|む]かう"),
        Question::from_ruby("どんなときもあきらめない[強|つよ]い[心|こころ]"),
        Question::from_ruby(
            "[友|とも][達|だち]と[一|いっ][緒|しょ]に[過|すご]す[楽|たの]しい[時|じ][間|かん]",
        ),
        Question::from_ruby("[隣|となり]の[客|きゃく]はよく[柿|かき][食|く]う[客|きゃく]だ"),
        Question::from_ruby("[長|なが]い[旅|たび]の[終|お]わりに[見|み]つけたもの"),
        Question::from_ruby(
            "[夏|なつ]の[夜|よ][空|ぞら]に[打|う]ち[上|あ]がる[大|おお]きな[花|はな][火|び]",
        ),
        Question::from_ruby(
            "[何|なに][事|ごと]にも[感|かん][謝|しゃ]の[気|き][持|も]ちを[忘|わす]れない",
        ),
        Question::from_ruby("[何|なに][事|ごと]も[経|けい][験|けん]が[次|つぎ]につながります"),
        Question::from_ruby("[何|なに]かご[不|ふ][明|めい]な[点|てん]はございますか"),
        Question::from_ruby("[生|なま][麦|むぎ][生|なま][米|ごめ][生|なま][卵|たまご]"),
        Question::from_ruby(
            "[二|に][兎|とう]を[追|お]う[者|もの]は[一|いっ][兎|とう]をも[得|え]ず",
        ),
        Question::from_ruby("[鳩|はと]が[豆|まめ][鉄|でっ][砲|ぽう]を[食|く]ったよう"),
        Question::from_ruby("[春|はる][風|かぜ]が[吹|ふ]いて[桜|さくら]が[舞|ま]い[散|ち]る"),
        Question::from_ruby("[人|ひと]のふり[見|み]てわがふり[直|なお]せ"),
        Question::from_ruby("[火|ひ]のないところに[煙|けむり]は[立|た]たぬ"),
        Question::from_ruby("[百|ひゃく][聞|ぶん]は[一|いっ][見|けん]にしかず"),
        Question::from_ruby("[冬|ふゆ]の[寒|さむ]い[日|ひ]に[温|あたた]かい[鍋|なべ]を[囲|かこ]む"),
        Question::from_ruby(
            "[坊|ぼう][主|ず]が[屏|びょう][風|ぶ]に[上|じょう][手|ず]に[坊|ぼう][主|ず]の[絵|え]を[描|か]いた",
        ),
        Question::from_ruby(
            "[本|ほん][日|じつ]はご[来|らい][場|じょう]いただきありがとうございます",
        ),
        Question::from_ruby(
            "[毎|まい][日|にち]のこつこつとした[積|つ]み[重|かさ]ねが[大|たい][切|せつ]です",
        ),
        Question::from_ruby(
            "[毎|まい][日|にち]の[健|けん][康|こう][管|かん][理|り]を[心|こころ][掛|が]ける",
        ),
        Question::from_ruby("またの[機|き][会|かい]を[楽|たの]しみにしております"),
        Question::from_ruby("[未|み][来|らい]に[向|む]かって[希|き][望|ぼう]の[橋|はし]をかける"),
        Question::from_ruby("[藪|やぶ]をつついて[蛇|へび]を[出|だ]す"),
        Question::from_ruby("よろしくお[願|ねが]いいたします"),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_problems_valid() {
        for difficulty in [Difficulty::Easy, Difficulty::Normal, Difficulty::Hard] {
            let pool = difficulty.pool();
            assert!(!pool.is_empty(), "{:?} の問題プールが空です", difficulty);
            for q in pool {
                assert!(!q.display.is_empty(), "display が空です");
                assert!(!q.reading.is_empty(), "reading が空です");
                assert!(!q.segments.is_empty(), "segments が空です");
            }
        }
    }
}
